//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketbaz.Database.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class anketbazEntities : DbContext
    {
        public anketbazEntities()
            : base("name=anketbazEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<answer> answers { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<guest> guests { get; set; }
        public DbSet<guestanswer> guestanswers { get; set; }
        public DbSet<poll> polls { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<user> users { get; set; }
    }
}
