//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketbaz.Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public long compid { get; set; }
        public string title { get; set; }
        public string sector { get; set; }
        public string crdat { get; set; }
        public string crtim { get; set; }
    }
}
