//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketbaz.Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class poll
    {
        public long pollid { get; set; }
        public long ownerid { get; set; }
        public string ownertype { get; set; }
        public string polltitle { get; set; }
        public string active { get; set; }
        public string iscookiecheck { get; set; }
        public string isipcheck { get; set; }
        public string isprivate { get; set; }
        public string ispassword { get; set; }
        public string isshowresult { get; set; }
        public string password { get; set; }
        public string fielddata { get; set; }
        public Nullable<int> viewcount { get; set; }
        public Nullable<long> crusr { get; set; }
        public string crdat { get; set; }
        public string crtim { get; set; }
    }
}
