//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketbaz.Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public long compid { get; set; }
        public long staffid { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string active { get; set; }
        public string isadmin { get; set; }
        public string authkey { get; set; }
        public string crdat { get; set; }
        public string crtim { get; set; }
    }
}
